spring:
  mvc:
    async:
      request-timeout: -1
  # Overridden when deployed to actual infrastructure.
  rabbitmq:
    host: localhost
    port: 5672

api:
  clientId: "choish20"
  url: "https://api.url.com"
  key: "github_action_key"