name: Run Test, Deploy to Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_registry:
    concurrency:
      group: deploy_registry
      cancel-in-progress: true
    name: Build and deploy docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: chmod +x ./gradlew && ./gradlew bootJar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Initialize Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build, Push to Registry
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: kangdroid/blockinfrastructure-plugin:${{ github.sha }},kangdroid/blockinfrastructure-plugin:main
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_kubernetes:
    concurrency:
      group: deploy_kubernetes
      cancel-in-progress: true
    name: Deploy to Kubernetes Cluster
    needs: [ deploy_registry ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_CLUSTER_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: blockinfrastructure
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/service.yaml
          images: |
            kangdroid/blockinfrastructure-plugin:${{ github.sha }}